// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3DnQIIFm6dTTpNYufT-m4mee6TkuK9Zs',
    appId: '1:114500384122:web:338afbf246430b473e92c3',
    messagingSenderId: '114500384122',
    projectId: 'lunchpedia-5ce81',
    authDomain: 'lunchpedia-5ce81.firebaseapp.com',
    storageBucket: 'lunchpedia-5ce81.appspot.com',
    measurementId: 'G-TEGFBDY6WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6w0cgl_oE_-jW8-l7PRT2xU9kU6hmjMo',
    appId: '1:114500384122:android:a083a2c2d50ddfdf3e92c3',
    messagingSenderId: '114500384122',
    projectId: 'lunchpedia-5ce81',
    storageBucket: 'lunchpedia-5ce81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6jW-VSSI7Mt_3Bbdwc9BThRbWbZNfNfQ',
    appId: '1:114500384122:ios:0755e5104397286b3e92c3',
    messagingSenderId: '114500384122',
    projectId: 'lunchpedia-5ce81',
    storageBucket: 'lunchpedia-5ce81.appspot.com',
    iosClientId: '114500384122-a5bt8pm3q0nqhrvr7jonmlb3omh9nnia.apps.googleusercontent.com',
    iosBundleId: 'com.kbs.lunchpedia',
  );
}
